/* eslint-disable */
// ┌──────────────────────────────────────────────────────────────────────┐
// │ AUTO-GENERATED by `npx dataverse-client generate`                   │
// │ DO NOT EDIT — regenerate with the CLI when your schema changes.     │
// └──────────────────────────────────────────────────────────────────────┘

/** Fields for the `service` table */
export interface Service {
  /** Unique service identifier */
  bookableresourcecategoryid?: string;
  /** Date created */
  createdon?: string;
  /** Service description */
  description?: string;
  /** Service name */
  name?: string;
  /** Record status */
  statecode?: number;
  /** Display label for statecode */
  statecode_label?: string;
  /** Buffer minutes between bookings for changeover */
  tn_bufferminutes?: number;
  /** Comma-separated search keywords (e.g. skip,tip,dump) */
  tn_searchaliases?: string;
  /** Slot duration in minutes for the availability grid */
  tn_slotdurationmins?: number;
}

/** Choice values for `service.statecode` */
export const ServiceStatecode = {
  /** Active */
  Active: 0,
  /** Inactive */
  Inactive: 1,
} as const;
export type ServiceStatecode = typeof ServiceStatecode[keyof typeof ServiceStatecode];

/** Fields for the `booking` table */
export interface Booking {
  /** Unique booking identifier */
  bookableresourcebookingid?: string;
  /** Booking status */
  bookingstatus?: string;
  /** GUID of the related status */
  _bookingstatus_value?: string;
  /** Booking type (Solid/Liquid) */
  bookingtype?: number;
  /** Display label for bookingtype */
  bookingtype_label?: string;
  /** Date created */
  createdon?: string;
  /** Duration in minutes */
  duration?: number;
  /** End time */
  endtime?: string;
  /** Date last modified */
  modifiedon?: string;
  /** Booking name */
  name?: string;
  /** Venue */
  resource?: string;
  /** GUID of the related venue */
  _resource_value?: string;
  /** Start time */
  starttime?: string;
  /** Record status */
  statecode?: number;
  /** Display label for statecode */
  statecode_label?: string;
  /** Status reason */
  statuscode?: number;
  /** Display label for statuscode */
  statuscode_label?: string;
}

/** Choice values for `booking.bookingtype` */
export const BookingBookingtype = {
  /** Liquid */
  Liquid: 2,
  /** Solid */
  Solid: 1,
} as const;
export type BookingBookingtype = typeof BookingBookingtype[keyof typeof BookingBookingtype];

/** Choice values for `booking.statecode` */
export const BookingStatecode = {
  /** Active */
  Active: 0,
  /** Inactive */
  Inactive: 1,
} as const;
export type BookingStatecode = typeof BookingStatecode[keyof typeof BookingStatecode];

/** Choice values for `booking.statuscode` */
export const BookingStatuscode = {
  /** Active */
  Active: 1,
  /** Inactive */
  Inactive: 2,
} as const;
export type BookingStatuscode = typeof BookingStatuscode[keyof typeof BookingStatuscode];

/** Fields for the `venue` table */
export interface Venue {
  /** Unique venue identifier */
  bookableresourceid?: string;
  /** Work hours calendar (for ExpandCalendar availability queries) */
  calendarid?: string;
  /** GUID of the related record */
  _calendarid_value?: string;
  /** Date created */
  createdon?: string;
  /** Venue name */
  name?: string;
  /** Resource type (e.g. Facility) */
  resourcetype?: number;
  /** Display label for resourcetype */
  resourcetype_label?: string;
  /** Record status */
  statecode?: number;
  /** Display label for statecode */
  statecode_label?: string;
  /** Status reason */
  statuscode?: number;
  /** Display label for statuscode */
  statuscode_label?: string;
  /** Timezone code (85 = GMT Standard Time) */
  timezone?: number;
}

/** Choice values for `venue.resourcetype` */
export const VenueResourcetype = {
  /** Generic */
  Generic: 1,
  /** Contact */
  Contact: 2,
  /** User */
  User: 3,
  /** Equipment */
  Equipment: 4,
  /** Account */
  Account: 5,
  /** Crew */
  Crew: 6,
  /** Facility */
  Facility: 7,
  /** Pool */
  Pool: 8,
} as const;
export type VenueResourcetype = typeof VenueResourcetype[keyof typeof VenueResourcetype];

/** Choice values for `venue.statecode` */
export const VenueStatecode = {
  /** Active */
  Active: 0,
  /** Inactive */
  Inactive: 1,
} as const;
export type VenueStatecode = typeof VenueStatecode[keyof typeof VenueStatecode];

/** Choice values for `venue.statuscode` */
export const VenueStatuscode = {
  /** Active */
  Active: 1,
  /** Inactive */
  Inactive: 2,
} as const;
export type VenueStatuscode = typeof VenueStatuscode[keyof typeof VenueStatuscode];

/** Fields for the `servicevenue` table */
export interface Servicevenue {
  /** Unique assignment identifier */
  bookableresourcecategoryassnid?: string;
  /** Date created */
  createdon?: string;
  /** Venue */
  resource?: string;
  /** GUID of the related venue */
  _resource_value?: string;
  /** Service */
  resourcecategory?: string;
  /** GUID of the related service */
  _resourcecategory_value?: string;
  /** Record status */
  statecode?: number;
  /** Display label for statecode */
  statecode_label?: string;
}

/** Choice values for `servicevenue.statecode` */
export const ServicevenueStatecode = {
  /** Active */
  Active: 0,
  /** Inactive */
  Inactive: 1,
} as const;
export type ServicevenueStatecode = typeof ServicevenueStatecode[keyof typeof ServicevenueStatecode];

/** Fields for the `calendar` table */
export interface Calendar {
  /** Calendar unique identifier */
  calendarid?: string;
  /** Calendar name */
  name?: string;
}

/** Fields for the `citizen` table */
export interface Citizen {
  /** Unique citizen identifier */
  contactid?: string;
  /** Date created */
  createdon?: string;
  /** Primary email address */
  emailaddress1?: string;
  /** First name */
  firstname?: string;
  /** Full name */
  fullname?: string;
  /** Last name */
  lastname?: string;
  /** Record status */
  statecode?: number;
  /** Display label for statecode */
  statecode_label?: string;
}

/** Choice values for `citizen.statecode` */
export const CitizenStatecode = {
  /** Active */
  Active: 0,
  /** Inactive */
  Inactive: 1,
} as const;
export type CitizenStatecode = typeof CitizenStatecode[keyof typeof CitizenStatecode];

/** Fields for the `servicebooking` table */
export interface Servicebooking {
  /** Date created */
  createdon?: string;
  /** Date last modified */
  modifiedon?: string;
  /** Record status */
  statecode?: number;
  /** Display label for statecode */
  statecode_label?: string;
  /** Status reason */
  statuscode?: number;
  /** Display label for statuscode */
  statuscode_label?: string;
  /** Underlying venue booking */
  tn_booking?: string;
  /** GUID of the related booking */
  _tn_booking_value?: string;
  /** Citizen who made the booking */
  tn_citizen?: string;
  /** GUID of the related citizen */
  _tn_citizen_value?: string;
  /** Unique service booking identifier */
  tn_citizenservicebookingid?: string;
  /** Duration in minutes */
  tn_duration?: number;
  /** Booking name / title */
  tn_name?: string;
  /** Free-text notes from the citizen */
  tn_notes?: string;
  /** Requested end time */
  tn_requestedend?: string;
  /** Requested start time */
  tn_requestedstart?: string;
  /** Service type (Leisure, Recycling, Sports, Community, Library, Registration) */
  tn_servicetype?: number;
  /** Display label for tn_servicetype */
  tn_servicetype_label?: string;
  /** Booking status (Requested, Confirmed, In Progress, Completed, Cancelled) */
  tn_status?: number;
  /** Display label for tn_status */
  tn_status_label?: string;
}

/** Choice values for `servicebooking.statecode` */
export const ServicebookingStatecode = {
  /** Active */
  Active: 0,
  /** Inactive */
  Inactive: 1,
} as const;
export type ServicebookingStatecode = typeof ServicebookingStatecode[keyof typeof ServicebookingStatecode];

/** Choice values for `servicebooking.statuscode` */
export const ServicebookingStatuscode = {
  /** Active */
  Active: 1,
  /** Inactive */
  Inactive: 2,
} as const;
export type ServicebookingStatuscode = typeof ServicebookingStatuscode[keyof typeof ServicebookingStatuscode];

/** Choice values for `servicebooking.tn_servicetype` */
export const ServicebookingTnServicetype = {
  /** Leisure */
  Leisure: 888000000,
  /** Recycling */
  Recycling: 888000001,
  /** Sports */
  Sports: 888000002,
  /** Community */
  Community: 888000003,
  /** Library */
  Library: 888000004,
  /** Registration */
  Registration: 888000005,
  /** Venue Hire */
  VenueHire: 888000006,
} as const;
export type ServicebookingTnServicetype = typeof ServicebookingTnServicetype[keyof typeof ServicebookingTnServicetype];

/** Choice values for `servicebooking.tn_status` */
export const ServicebookingTnStatus = {
  /** Requested */
  Requested: 888000000,
  /** Confirmed */
  Confirmed: 888000001,
  /** In Progress */
  InProgress: 888000002,
  /** Completed */
  Completed: 888000003,
  /** Cancelled */
  Cancelled: 888000004,
} as const;
export type ServicebookingTnStatus = typeof ServicebookingTnStatus[keyof typeof ServicebookingTnStatus];

/** Fields for the `status` table */
export interface Status {
  /** Unique status identifier */
  bookingstatusid?: string;
  /** Date created */
  createdon?: string;
  /** Status name (e.g. Scheduled, Canceled) */
  name?: string;
  /** Record status */
  statecode?: number;
  /** Display label for statecode */
  statecode_label?: string;
  /** Status code */
  status?: number;
  /** Display label for status */
  status_label?: string;
}

/** Choice values for `status.statecode` */
export const StatusStatecode = {
  /** Active */
  Active: 0,
  /** Inactive */
  Inactive: 1,
} as const;
export type StatusStatecode = typeof StatusStatecode[keyof typeof StatusStatecode];

/** Choice values for `status.status` */
export const StatusStatus = {
  /** Proposed */
  Proposed: 1,
  /** Committed */
  Committed: 2,
  /** Canceled */
  Canceled: 3,
} as const;
export type StatusStatus = typeof StatusStatus[keyof typeof StatusStatus];

/** All valid table names accepted by the API */
export type TableName = "service" | "booking" | "venue" | "servicevenue" | "calendar" | "citizen" | "servicebooking" | "status" | "services" | "category" | "categories" | "bookableresourcecategory" | "bookableresourcecategories" | "bookings" | "slot" | "slots" | "resourcebooking" | "bookableresourcebooking" | "bookableresourcebookings" | "venues" | "facility" | "facilities" | "resource" | "resources" | "bookableresource" | "bookableresources" | "servicevenues" | "servicelink" | "servicelinks" | "categoryassignment" | "categoryassignments" | "bookableresourcecategoryassn" | "bookableresourcecategoryassns" | "calendars" | "citizens" | "contact" | "contacts" | "servicebookings" | "citizenbooking" | "citizenbookings" | "mybooking" | "mybookings" | "tn_citizenservicebooking" | "tn_citizenservicebookings" | "statuses" | "bookingstatus" | "bookingstatuses";
